version: '3'

services:

  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #   restart: always
  #   logging:
  #     driver: ${LOGGING_DRIVER:-json-file}

  # postgres:
  #   # No need to specify port info as networkig will be handled by compose.
  #   # Those lines are kept as comments as the web server is tested locally before 
  #   # running `docker-compose up` to avoid rebuilding the image at each modification
  #   # in the server code. (the first compilation stage takes a decent amount of time,
  #   # it needs to be cached and handled more carefully)
    
  #   image: postgres
  #   restart: always
  #   expose:
  #     - 5432
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=iamproof
  #     - POSTGRES_PASSWORD=GenProof23!!
  #     - POSTGRES_DB=proof_db
  #     # - POSTGRES_HOST_AUTH_METHOD=trust
  #   volumes:
  #     - db_data:/var/lib/postgresql/data

  # services for alt-ergo job queries
  alt-ergo-2.4.1:
    image: elias2049/ae_mono:alt-ergo.2.4.1-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock

  alt-ergo-2.4.0:
    image: elias2049/ae_mono:alt-ergo.2.4.0-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock
  
  alt-ergo-2.3.3:
    image: elias2049/ae_mono:alt-ergo.2.3.3-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock
  
  alt-ergo-2.3.2:
    image: elias2049/ae_mono:alt-ergo.2.3.2-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock

  alt-ergo-2.3.1:
    image: elias2049/ae_mono:alt-ergo.2.3.1-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock

  alt-ergo-2.3.0:
    image: elias2049/ae_mono:alt-ergo.2.3.0-slim
    restart: always
    # volumes:
    #   - job_stock:/home/ocaml/job_stock

volumes:
  db_data:
    # driver: flocker
    # driver_opts:
    #   size: "5GiB"
  # job_stock: # Currently writing to local folder as server is tested locally
  